In [ ]:
import numpy as np

In [ ]:
#Recap
arr = np.array([[1,2,3,],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#Dot product-m×n||n×p
arr1=np.random.randint(1,2,(3,1))

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr1.shape

(3, 1)

In [ ]:
result= np.dot(arr,arr1)

In [ ]:
print(result)

[[ 6]
 [15]]


In [ ]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[19 14 14]
 [11 14 12]
 [18 13 18]]


In [34]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#r1.I
result2=np.dot(r1,r2)

In [37]:
print(result2)

[[19. 14. 14.]
 [11. 14. 12.]
 [18. 13. 18.]]


In [38]:
#M.I=.M=I
#A.B!=B.A

In [39]:
#Mathematical Operations
#+-*/
t1=np.random .randint (3,6,(3,3))
t2=np.random .randint (3,6,(3,3))

In [40]:
print(t1)
print(t2)

[[5 4 5]
 [4 3 3]
 [5 3 3]]
[[4 4 4]
 [3 5 4]
 [4 5 3]]


In [42]:
t3=t1+t2

In [43]:
print(t3)

[[9 8 9]
 [7 8 7]
 [9 8 6]]


In [44]:
#matrix multiplication
result= np.dot(arr,arr1)

In [47]:
#statistical operations
mean= t3.mean()
mode=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [46]:
print(mean)

7.888888888888889


In [48]:
print(mode)

9


In [50]:
print(median)

8.0


In [51]:
print(var)

0.9876543209876544


In [52]:
std*std
print(var)

0.9876543209876544


In [53]:
std*std

0.9876543209876545

In [59]:
#Trignometric functions
#Sin(x)
#Cos(x)
#Tan(x)-Sin(x)/Cos(x)
#Cosec-1/Sin(x)
#Sec-1/Cos(x)
#cot-1/Tan(x)
#
angles=np.array([0,15,31,45,60,75,90])
#Sin(array)
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [60]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.51503807 0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.57167301e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 6.00860619e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [65]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr=arr.reshape(3,2)
print(reshapedarr)
#cover/Faltten any n dim array
flattendarr=arr.flatten()
print(flattendarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [66]:
#stacking the data

arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 is{arr3.shape}")


#Horizontalstacking
arr4=np.vstack((arr1,arr2))
print(f"The shape of arr4 is{arr3.shape}")

The shape of arr3 is(2, 4)
The shape of arr4 is(2, 4)


In [69]:
#Filtering
arr=np.array([10,20,30,40,50,60,70,80,90])
farr=arr[arr>40]
print(farr)

[50 60 70 80 90]
